#!/usr/bin/env bash

command -v psql >/dev/null 2>&1 || {
    echo >&2 'psql is a required prerequisite, it is currently not installed.'
    exit 1
}

PGHOST=localhost PGPORT=54324 PGUSER=pguser PGPASSWORD=pgpass PGDATABASE=mintery psql
