#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -u

set -a
source ./env
set +a

[ -z $ORIGINATOR_ADDRESS ] && echo 'ORIGINATOR_ADDRESS not defined in env' && exit 1
[ -z $ORIGINATOR_PRIV_KEY ] && echo 'ORIGINATOR_PRIV_KEY not defined in env' && exit 1

export CONTRACT=${CONTRACT:-'fa2_multi_asset'}
export NODE_URL=${NODE_URL:-'https://ithacanet.ecadinfra.com'}
export BURN_CAP=${BURN_CAP:-'0.1'}

INITIAL_STORAGE=`envsubst < contracts/${CONTRACT}.storage`

docker run \
    -it \
    -v "$PWD/contracts/${CONTRACT}.tz":/tmp/contract.tz \
    --entrypoint /bin/sh \
    tezos/tezos:v13-release \
    -c "
        tezos-client --endpoint $NODE_URL import secret key originator_address "unencrypted:$ORIGINATOR_PRIV_KEY" || exit 1
        tezos-client --endpoint $NODE_URL --wait 1 originate contract $CONTRACT transferring 0 from originator_address running /tmp/contract.tz --init '$INITIAL_STORAGE' --burn-cap $BURN_CAP
    " | tee log/deploy.log || exit 1

cat log/deploy.log | grep --quiet 'Fatal error' && exit 1

contract_address=`
    cat log/deploy.log \
        | grep --basic-regexp '^New contract .* originated\.' \
        | awk -F' ' '{print $3}'`
./script/replace-env CONTRACT_ADDRESS "\"$contract_address\""
echo "contract deployed. address: $contract_address"
