#!/usr/bin/env bash
git_root=`git rev-parse --show-toplevel`
cd "$git_root"/smart-contract-helper

set -u

docker-compose down

source "$git_root"/.env

[ -z $ADMIN_ADDRESS ] && echo 'ADMIN_ADDRESS not defined in .env' && exit 1
[ -z $ORIGINATOR_PRIVATE_KEY ] && echo 'ORIGINATOR_PRIVATE_KEY not defined in .env' && exit 1
export NODE_URL=${NODE_URL:-'http://art-basel.tzconnect.berlin:18732'}

export ADMIN_ADDRESS
export ORIGINATOR_PRIVATE_KEY


# yarn install
yarn install -g || exit 1
yarn build || exit 1

yarn run smart-contract.helper compile-contract || exit 1
yarn run smart-contract.helper deploy-contract | tee $git_root/log/deploy.log || exit 1

cd "$git_root"
contract=`
    cat "$git_root"/log/deploy.log \
        | grep 'Contract deployed at' \
        | awk -F':' '{print $2}' \
        | sed 's/\ *//g'`


sed -i "s/address:.*/address:\ \"$contract\"/g" config/kanvas.yaml
sed -i "s/\"nftContract\":.*/\"nftContract\":\ \"$contract\",/g" config/peppermint_config.json
sed -i "s/\"privateKey\":.*/\"privateKey\":\ \"$ORIGINATOR_PRIVATE_KEY\",/g" config/peppermint_config.json

echo 'contract deployed. now `docker-compose up` can be run'
