#!/usr/bin/env bash
git_root=`git rev-parse --show-toplevel`

set -u


command -v jq >/dev/null 2>&1 || {
    echo >&2 'jq is a required prerequisite, it is currently not installed.'
    exit 1
}

touch $git_root/.env

echo "please:
1). visit https://teztnets.xyz/ithacanet-faucet
2). pass the anti bot test
3). then copy paste what is in the text box below \"Here is your activation key:\" into this terminal
...
"
"$git_root"/script/read-json > /tmp/faucet.json || exit 1

NODE_URL=${NODE_URL:-'https://ithaca-archive.tzconnect.berlin'}
docker run \
    -it \
    --dns 8.8.8.8 --dns 10.252.252.252 \
    -v /tmp/faucet.json:/tmp/faucet.json \
    --entrypoint /bin/sh \
    tezos/tezos:latest-release \
    -c "
        tezos-client --endpoint $NODE_URL activate account faucet with /tmp/faucet.json || exit 1
        pwd
        ls .tezos-client
        exit
    " | tee "$git_root"/log/initialize-address.log || exit 1

pub=`
    awk '/^Account faucet \(/,EOF { print $0 }' "$git_root"/log/initialize-address.log \
    | tail -n +2 \
    | jq '.public_keys[].value'`

priv=`
    awk '/^Account faucet \(/,EOF { print $0 }' "$git_root"/log/initialize-address.log \
    | tail -n +2 \
    | jq '.private_keys[].value' \
    | sed 's/unencrypted://g'`

"$git_root"/script/replace-env ADMIN_ADDRESS "$pub"
"$git_root"/script/replace-env ORIGINATOR_PRIVATE_KEY "$priv"
