#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -u


command -v jq >/dev/null 2>&1 || {
    echo >&2 'jq is a required prerequisite, it is currently not installed.'
    exit 1
}

NODE_URL=${NODE_URL:-'https://ghostnet-archive.tzconnect.berlin'}
addr_gen_res=`docker run tezos/tezos:latest tezos-client --endpoint $NODE_URL stresstest gen keys 1`

pkh=`echo "$addr_gen_res" | jq -r '.[0].pkh'`
pk=`echo "$addr_gen_res" | jq -r '.[0].pk'`
sk=`echo "$addr_gen_res" | jq -r '.[0].sk'`

touch ./env

./script/replace-env ORIGINATOR_ADDRESS "$pkh"
./script/replace-env ORIGINATOR_PUB_KEY "$pk"
./script/replace-env ORIGINATOR_PRIV_KEY "$sk"

echo "please:
1). visit https://faucet.ghostnet.teztnets.xyz
2). enter "$pkh" into the box in section 'Or fund any address'
3). press 'request 6001 tez' in that same section
4). this script will continue to wait until the tez has arrived into the account"

while [ `http https://api.ghostnet.tzkt.io/v1/accounts/$pkh/balance` -eq 0 ]; do
    echo -n '.'
    sleep 1
done
echo
echo "fresh address $pkh initialized"
