#!/usr/bin/env sh

command -v jq >/dev/null 2>&1 || {
    echo >&2 'jq is a required prerequisite, it is currently not installed.'
    exit 1
}

data=''
while read text; do
    data="$data
$text"

    echo "$data" | jq '.' >/dev/null 2>&1 && break
done
echo "$data"
