#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
cd $SCRIPT_DIR/..

set -u

var=$1
val=$2

if grep "^$var=" .env >/dev/null ; then
    sed -i'.bak' "s/^$var=.*$/$var=$val/" .env
    rm .env.bak
else
    echo "$var=$val" >> .env
fi
