#!/usr/bin/env bash
git_root=`git rev-parse --show-toplevel`
cd "$git_root"

set -u

var=$1
val=$2

if grep "^$var=" .env >/dev/null ; then
    sed -i'.bak' "s/^$var=.*$/$var=$val/" .env
    rm .env.bak
else
    echo "$var=$val" >> .env
fi
